version: '3'

services:
  api-gateway:
    build: .
    container_name: api-gateway
    external_links:
      - volume-service
      - density-service
      - semantic-service
    ports:
      - "8080:8080"
    restart: always
    networks:
      - default
      - volume-of-vehicles-cpp_default
      - density-of-vehicles_default
      - semantic_default

networks:
  volume-of-vehicles-cpp_default:
    external: true
  density-of-vehicles_default:
    external: true
  semantic_default:
    external: true